export const OperationDescription: {[key: string]: string} = {
    "4031": "Asignación de N.I.E.",
    "4032": "Certificado de residente o no residente",
    "22": "CERTIFICADOS UE",
    "4118": "POLICIA - CERTIFICADOS CONCORDANCIA",
    "4036": "POLICIA - RECOGIDA DE TARJETA DE IDENTIDAD DE EXTRANJERO (TIE)",
    "4067": "POLICIA- EXPEDICIÓN/RENOVACIÓN DE DOCUMENTOS DE SOLICITANTES DE ASILO",
    "4078": "POLICIA- SOLICITUD ASILO",
    "4037": "POLICIA-CARTA DE INVITACIÓN",
    "4038": "POLICIA-CERTIFICADO DE REGISTRO DE CIUDADANO DE LA U.E.",
    "4010": "POLICIA-TOMA DE HUELLA (EXPEDICIÓN DE TARJETA), RENOVACIÓN DE TARJETA DE LARGA DURACIÓN Y DUPLICADO",
    "4111": "POLICÍA - UCRANIA : SOLICITUD PROTECCIÓN TEMPORAL DESPLAZADOS",
    "4112": "POLICÍA TARJETA CONFLICTO UCRANIA–ПОЛІЦІЯ -КАРТКА ДЛЯ ПЕРЕМІЩЕНИХ ОСІБ ВНАСЛІДОК КОНФЛІКТУ В УКРАЇНІ",
};
