export const Provincia: {[key: string]: string} = {
    "A Coruña": "/icpplus/citar?p=15&locale=es",
    "Albacete": "/icpplus/citar?p=2&locale=es",
    "Alicante": "/icpco/citar?p=3&locale=es",
    "Almería": "/icpplus/citar?p=4&locale=es",
    "Araba": "/icpplus/citar?p=1&locale=es",
    "Asturias": "/icpplus/citar?p=33&locale=es",
    "Ávila": "/icpplus/citar?p=5&locale=es",
    "Badajoz": "/icpplus/citar?p=6&locale=es",
    "Barcelona": "/icpplustieb/citar?p=8&locale=es",
    "Bizkaia": "/icpplus/citar?p=48&locale=es",
    "Burgos": "/icpplus/citar?p=9&locale=es",
    "Cáceres": "/icpplus/citar?p=10&locale=es",
    "Cádiz": "/icpplus/citar?p=11&locale=es",
    "Cantabria": "/icpplus/citar?p=39&locale=es",
    "Castellón": "/icpplus/citar?p=12&locale=es",
    "Ceuta": "/icpplus/citar?p=51&locale=es",
    "Ciudad Real": "/icpplus/citar?p=13&locale=es",
    "Córdoba": "/icpplus/citar?p=14&locale=es",
    "Cuenca": "/icpplus/citar?p=16&locale=es",
    "Gipuzkoa": "/icpplus/citar?p=20&locale=es",
    "Girona": "/icpplus/citar?p=17&locale=es",
    "Granada": "/icpplus/citar?p=18&locale=es",
    "Guadalajara": "/icpplus/citar?p=19&locale=es",
    "Huelva": "/icpplus/citar?p=21&locale=es",
    "Huesca": "/icpplus/citar?p=22&locale=es",
    "Illes Balears": "/icpco/citar?p=7&locale=es",
    "Jaén": "/icpplus/citar?p=23&locale=es",
    "La Rioja": "/icpplus/citar?p=26&locale=es",
    "Las Palmas": "/icpco/citar?p=35&locale=es",
    "León": "/icpplus/citar?p=24&locale=es",
    "Lleida": "/icpplus/citar?p=25&locale=es",
    "Lugo": "/icpplus/citar?p=27&locale=es",
    "Madrid": "/icpplustiem/citar?p=28&locale=es",
    "Málaga": "/icpco/citar?p=29&locale=es",
    "Melilla": "/icpplus/citar?p=52&locale=es",
    "Murcia": "/icpplus/citar?p=30&locale=es",
    "Navarra": "/icpplus/citar?p=31&locale=es",
    "Ourense": "/icpplus/citar?p=32&locale=es",
    "Palencia": "/icpplus/citar?p=34&locale=es",
    "Pontevedra": "/icpplus/citar?p=36&locale=es",
    "Salamanca": "/icpplus/citar?p=37&locale=es",
    "S.Cruz Tenerife": "/icpco/citar?p=38&locale=es",
    "Segovia": "/icpplus/citar?p=40&locale=es",
    "Sevilla": "/icpplus/citar?p=41&locale=es",
    "Soria": "/icpplus/citar?p=42&locale=es",
    "Tarragona": "/icpplus/citar?p=43&locale=es",
    "Teruel": "/icpplus/citar?p=44&locale=es",
    "Toledo": "/icpplus/citar?p=45&locale=es",
    "Valencia": "/icpplus/citar?p=46&locale=es",
    "Valladolid": "/icpplus/citar?p=47&locale=es",
    "Zamora": "/icpplus/citar?p=49&locale=es",
    "Zaragoza": "/icpplus/citar?p=50&locale=es"
};
